import pandas as pd
import json
import os
import sys
from data_loader import fetch_stock_data, fetch_market_news
from feature_engineering import add_technical_indicators, analyze_sentiment
from model import train_model, predict_next_move

def main():
    # Allow passing ticker as argument
    if len(sys.argv) > 1:
        TICKER = sys.argv[1]
    else:
        TICKER = "RELIANCE.NS" # Example: Reliance Industries default

    print(f"--- Starting Quantitative Analysis for {TICKER} ---")

    # 1. Get Data
    df = fetch_stock_data(TICKER)
    news = fetch_market_news(keywords=['India Stock Market', 'Sensex', 'Nifty', TICKER, 'Global Economy', 'War', 'Geopolitics'])
    
    if df.empty:
        print(f"No stock data found for {TICKER}.")
        return

    # 2. Feature Engineering & Sentiment
    df_tech = add_technical_indicators(df)
    
    if df_tech.empty:
        print("Not enough data to calculate indicators.")
        return

    sentiment_score = analyze_sentiment(news)
    print(f"Global/News Sentiment Score: {sentiment_score:.4f}")

    # 3. Train Model
    model = train_model(df_tech)

    # 4. Predict
    prob_buy = predict_next_move(model, df_tech, sentiment_score)
    
    signal = "HOLD"
    if prob_buy > 0.6:
        signal = "BUY"
    elif prob_buy < 0.4:
        signal = "SELL"
    
    print(f"Prediction: Probability of UP move: {prob_buy:.2f} -> Signal: {signal}")

    # 5. Output JSON for ClawDBot
    output = {
        "ticker": TICKER,
        "signal": signal,
        "probability": round(prob_buy, 4),
        "sentiment": round(sentiment_score, 4),
        "timestamp": pd.Timestamp.now().isoformat(),
        "notes": "Generated by Indian Stock Quant Model"
    }

    # Save to a file (optional)
    with open("trade_signal.json", "w") as f:
        json.dump(output, f, indent=4)
        
    # Also print to stdout for easy pipe/read
    print("\n--- JSON OUTPUT ---")
    print(json.dumps(output, indent=4))
    print("-------------------")
    
    print("Signal saved to trade_signal.json")

if __name__ == "__main__":
    main()
